[green_agent]
image = "ghcr.io/rdi-foundation/terminal-bench-green"
env = { LOG_LEVEL = "INFO" }

[[participants]]
image = "ghcr.io/rdi-foundation/terminal-bench-dummy-purple"
name = "agent"
env = {}

[config]
concurrency=3
